// Redakčne spravovateľný štartovací katalóg pre slovenský trh, vrátane jazdených modelov.
// Nie je to úradný ani nemenný zoznam všetkých historických modelov. V ostrej verzii ho spravuje CRM.
const catalog={
  'Abarth':['500','595','695','124 Spider'],
  'Acura':['Integra','MDX','RDX','TL','TLX'],
  'Aiways':['U5','U6'],
  'Aixam':['City','Coupé','Crossline','Crossover','Mega'],
  'Alfa Romeo':['147','156','159','166','4C','Giulia','Giulietta','Junior','MiTo','Stelvio','Tonale'],
  'Alpine':['A110','A290'],
  'Aston Martin':['DB9','DB11','DB12','DBS','DBX','Vantage','Vanquish'],
  'Audi':['80','100','A1','A2','A3','A4','A5','A6','A7','A8','e-tron','Q2','Q3','Q4 e-tron','Q5','Q6 e-tron','Q7','Q8','R8','RS3','RS4','RS5','RS6','S3','S4','S5','S6','TT'],
  'Bentley':['Bentayga','Continental GT','Flying Spur','Mulsanne'],
  'BMW':['Rad 1','Rad 2','Rad 3','Rad 4','Rad 5','Rad 6','Rad 7','Rad 8','i3','i4','i5','i7','iX','iX1','iX2','iX3','M2','M3','M4','M5','X1','X2','X3','X4','X5','X6','X7','XM','Z4'],
  'Buick':['Enclave','Encore','Regal'],
  'BYD':['Atto 3','Dolphin','Han','Seal','Seal U','Tang'],
  'Cadillac':['ATS','CT5','Escalade','Lyriq','SRX','XT4','XT5'],
  'Chevrolet':['Aveo','Camaro','Captiva','Corvette','Cruze','Kalos','Lacetti','Malibu','Orlando','Spark','Trax','Volt'],
  'Chrysler':['200','300C','Grand Voyager','Pacifica','PT Cruiser','Voyager'],
  'Citroën':['Berlingo','C1','C2','C3','C3 Aircross','C4','C4 Cactus','C4 Picasso','C5','C5 Aircross','C6','C8','DS3','DS4','DS5','Jumper','Jumpy','SpaceTourer'],
  'Cupra':['Ateca','Born','Formentor','Leon','Tavascan','Terramar'],
  'Dacia':['Bigster','Dokker','Duster','Jogger','Lodgy','Logan','Sandero','Spring'],
  'Daewoo':['Espero','Kalos','Lanos','Leganza','Matiz','Nubira','Tacuma'],
  'Daihatsu':['Charade','Cuore','Sirion','Terios'],
  'Dodge':['Caliber','Challenger','Charger','Durango','Journey','Nitro','Ram'],
  'Dongfeng':['Box','Forthing T5 Evo','M-Hero 917','Voyah Free'],
  'DS':['DS 3','DS 4','DS 5','DS 7','DS 9'],
  'Ferrari':['296','458','488','812','California','F8','Portofino','Purosangue','Roma','SF90'],
  'Fiat':['124 Spider','500','500e','500L','500X','Bravo','Croma','Doblo','Ducato','Fiorino','Freemont','Grande Panda','Grande Punto','Panda','Punto','Qubo','Scudo','Sedici','Tipo'],
  'Fisker':['Ocean'],
  'Ford':['B-Max','Bronco','C-Max','EcoSport','Edge','Escape','Explorer','Fiesta','Focus','Fusion','Galaxy','Ka','Kuga','Mondeo','Mustang','Mustang Mach-E','Puma','Ranger','S-Max','Tourneo Connect','Tourneo Custom','Transit','Transit Connect','Transit Custom'],
  'Geely':['Coolray','Emgrand','Monjaro','Starray'],
  'Genesis':['G70','G80','G90','GV60','GV70','GV80'],
  'GMC':['Acadia','Sierra','Terrain','Yukon'],
  'Honda':['Accord','Civic','CR-V','e','FR-V','HR-V','Insight','Jazz','Legend','NSX','Odyssey','Prelude','ZR-V'],
  'Hummer':['H2','H3','EV'],
  'Hyundai':['Bayon','Getz','i10','i20','i30','i40','Ioniq','Ioniq 5','Ioniq 6','ix20','ix35','Kona','Nexo','Santa Fe','Sonata','Staria','Tucson'],
  'Infiniti':['EX','FX','Q30','Q50','Q60','QX30','QX50','QX70'],
  'Isuzu':['D-Max','MU-X'],
  'Iveco':['Daily','Eurocargo'],
  'Jaguar':['E-Pace','F-Pace','F-Type','I-Pace','S-Type','XE','XF','XJ','X-Type'],
  'Jeep':['Avenger','Cherokee','Commander','Compass','Grand Cherokee','Patriot','Renegade','Wrangler'],
  'Kia':['Carens','Ceed','e-Niro','EV3','EV4','EV6','EV9','Niro','Optima','Picanto','ProCeed','Rio','Sorento','Soul','Sportage','Stinger','Stonic','Venga','XCeed'],
  'Lada':['Granta','Kalina','Niva','Samara','Vesta'],
  'Lamborghini':['Aventador','Gallardo','Huracán','Revuelto','Urus'],
  'Lancia':['Delta','Musa','Phedra','Thesis','Ypsilon'],
  'Land Rover':['Defender','Discovery','Discovery Sport','Freelander','Range Rover','Range Rover Evoque','Range Rover Sport','Range Rover Velar'],
  'Leapmotor':['C10','T03'],
  'Lexus':['CT','ES','GS','IS','LBX','LC','LS','LX','NX','RC','RX','RZ','UX'],
  'Lincoln':['Aviator','Continental','Corsair','MKC','MKX','Navigator'],
  'Lotus':['Elise','Emeya','Eletre','Emira','Evora','Exige'],
  'Lucid':['Air','Gravity'],
  'Lynk & Co':['01','02','08'],
  'Maserati':['Ghibli','GranCabrio','GranTurismo','Grecale','Levante','MC20','Quattroporte'],
  'Mazda':['2','3','5','6','CX-3','CX-30','CX-5','CX-60','CX-80','CX-9','MX-5','MX-30','RX-8'],
  'McLaren':['570S','600LT','720S','750S','Artura','GT','MP4-12C'],
  'Mercedes-Benz':['Trieda A','Trieda B','Trieda C','Trieda E','Trieda G','Trieda S','CLA','CLS','CLE','EQA','EQB','EQC','EQE','EQS','GLA','GLB','GLC','GLE','GLS','AMG GT','SL','Sprinter','Vito','Trieda V'],
  'MG':['3','4','5','Cyberster','HS','Marvel R','ZS'],
  'Mini':['Cooper','Clubman','Countryman','Paceman'],
  'Mitsubishi':['ASX','Colt','Eclipse Cross','L200','Lancer','Outlander','Pajero','Space Star'],
  'Nissan':['350Z','370Z','Almera','Ariya','Juke','Leaf','Micra','Murano','Navara','Note','Pathfinder','Patrol','Primera','Pulsar','Qashqai','Townstar','X-Trail'],
  'Opel':['Adam','Agila','Ampera','Antara','Astra','Cascada','Combo','Corsa','Crossland','Frontera','Grandland','Insignia','Meriva','Mokka','Movano','Signum','Vectra','Vivaro','Zafira'],
  'Peugeot':['107','108','206','207','208','2008','307','308','3008','407','408','4008','508','5008','607','807','Boxer','Expert','Partner','Rifter','Traveller'],
  'Polestar':['1','2','3','4','5'],
  'Pontiac':['Firebird','G6','Grand Prix'],
  'Porsche':['718 Boxster','718 Cayman','911','Cayenne','Macan','Panamera','Taycan'],
  'RAM':['1500','2500','3500'],
  'Renault':['Arkana','Austral','Captur','Clio','Espace','Fluence','Kadjar','Kangoo','Koleos','Laguna','Master','Mégane','Mégane E-Tech','Rafale','Scénic','Symbioz','Talisman','Trafic','Twingo','Zoe'],
  'Rolls-Royce':['Cullinan','Ghost','Phantom','Spectre','Wraith'],
  'Rover':['25','45','75','Streetwise'],
  'Saab':['9-3','9-5'],
  'Seat':['Alhambra','Altea','Arona','Ateca','Cordoba','Exeo','Ibiza','Leon','Tarraco','Toledo'],
  'Smart':['#1','#3','Forfour','Fortwo','Roadster'],
  'SsangYong':['Actyon','Korando','Kyron','Musso','Rexton','Tivoli','Torres'],
  'Subaru':['BRZ','Crosstrek','Forester','Impreza','Justy','Legacy','Levorg','Outback','Solterra','XV'],
  'Suzuki':['Across','Alto','Baleno','Grand Vitara','Ignis','Jimny','S-Cross','Splash','Swift','SX4','Vitara'],
  'Škoda':['Citigo','Elroq','Enyaq','Fabia','Favorit','Felicia','Kamiq','Karoq','Kodiaq','Octavia','Rapid','Roomster','Scala','Superb','Yeti'],
  'Tesla':['Model 3','Model S','Model X','Model Y','Cybertruck'],
  'Toyota':['Auris','Avensis','Aygo','Aygo X','bZ4X','C-HR','Camry','Corolla','GR86','Hilux','Land Cruiser','Mirai','Prius','Proace','RAV4','Supra','Verso','Yaris','Yaris Cross'],
  'Volkswagen':['Amarok','Arteon','Beetle','Bora','Caddy','Caravelle','Crafter','Golf','ID.3','ID.4','ID.5','ID.7','Jetta','Multivan','Passat','Polo','Scirocco','Sharan','T-Cross','T-Roc','Taigo','Tiguan','Touareg','Touran','Transporter','Up!'],
  'Volvo':['C30','C40','EX30','EX40','EX90','S40','S60','S80','S90','V40','V50','V60','V70','V90','XC40','XC60','XC70','XC90'],
  'Voyah':['Dream','Free','Passion'],
  'Zeekr':['001','7X','X']
};
